# Generated by Django 5.1.3 on 2024-11-27 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_alter_category_options_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="categories",
            new_name="category",
        ),
    ]
